# Generated by Django 4.0.2 on 2022-03-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='matric_number',
        ),
    ]
