# Generated by Django 4.0.2 on 2022-03-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_comment_email_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email_address',
            field=models.EmailField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='home_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='matric_number',
            field=models.SlugField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='middlename',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='next_of_kin',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
