# Generated by Django 4.0.2 on 2022-03-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_comment_email_address_comment_home_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='middlename',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
